### ISSUE TITLE
PhysFS?

### ISSUE THREAD

**Issue by RobLoach** [C-Chads/C-Chads#1]
[PhysFS](https://icculus.org/physfs/) is hosted using Mercurial over at https://hg.icculus.org/icculus/physfs/

What are your thoughts on having a git fork of it, bringing in the Hg history? There's a couple that exist already, but it looks like they're pretty old.

**Comment by gek169** [comment]
An interesting idea. It looks like it's a game data format library. I wonder if it parses Iwads?

I like the idea of making a git repo for it, surprising they're not already using git.

**Comment by RobLoach** [comment]
> I wonder if it parses Iwads?

DOOM Wads work! Was likely originally inspired by Quake's .pak system. Ryan C. Gordon is a legend.

> I like the idea of making a git repo for it, surprising they're not already using git.

PhysFS began when git didn't exist :wink:

**Comment by gek169** [comment]
I'm forking it right now, I think this was a good spot

**Comment by gek169** [comment]
https://github.com/C-Chads/PhysicsFS-Fork
Good spotting, thank you.
I hope this fork helps people use the library (as it will now be easier to clone and run)

The library compiles successfully on my machine but for whatever reason, the tests fail to find the SO file in the same directory. I'm guessing it wants its SO installed?
