### ISSUE TITLE
I'd like to join

### ISSUE THREAD

**Issue by kevidryon2** [C-Chads/C-Chads#10]
I've used C for 5-6 months, and I'd like to join.

- I never used Rust
- I use Linux and FOSS
- I created some libraries (For example, `libupix`, which is a pixel library I've used in some projects)
- I strictly use GCC

I also really like low-level programming, and thus I have some experience with ARM, Z80, and Intel Assembly.

**Comment by gek169** [comment]
sounds good

**Comment by gek169** [comment]
alright you're a member now so i'm closing this one
