### ISSUE TITLE
Where have the group posts gone?

### ISSUE THREAD

**Issue by bztsrc** [C-Chads/C-Chads#11]
Sorry for the issue, but I can't seem to find the group posts interface on gh any more....

Anyway, what I could find is [this](https://github.com/orgs/C-Chads/teams/all-members/members/archived_team_posts.json). I have a pretty neat MIT licensed packaging solution written as an ANSI C library, that you might find interesting: [syspkg](https://gitlab.com/bztsrc/syspkg).

I've also seen @gek169 's issues on TIC-80. I think they might have misunderstood you and your conversation started on the wrong foot. However I agree, TIC-80's documentation is terrible (currently I'm struggling with the sfx and music stuff). On that note, I'd like ask your (singular, but also plural for C-Chads members) opinion on a similar to TIC-80 project I made. Its documentation is [here](https://bztsrc.gitlab.io/meg4/manual_en.html). What do you think, is this a good doc? Which parts do I need to improve? (The project itself is pretty recent, there might be still bugs lurking in the shadows, but feel free to give it a spin. Currently I'm working on integrating TinyGL into it and replace my not-so-efficient implementation for [tri3d](https://bztsrc.gitlab.io/meg4/manual_en.html#tri3d)).

And again, sorry about communicating this way, please advice where can I find the group posts (not just the json archive) on github?

Cheers,
bzt

**Comment by gek169** [comment]
Oh yeah, I remember, I didn't find the github wiki feature for TIC-80's docs.
Yes, Meg-4's docs look quite nice. I think it's well formatted. If it's displayed prominently then it should be easy to find

Also, I might be able to help you with tinygl.
TinyGL was optimized by F. Bellard for old CPUs. the trirast code should be updated to use vector cross products to check whether a point is inside a triangle rather than using scanline techniques if you want it to go superspeed on a modern CPU (to take advantage of SIMD and whatnot)

**Comment by bztsrc** [comment]
Hi,

> I didn't find the github wiki feature for TIC-80's docs.

Yeah, and even if you've found it, you'll realize it is lacking on many topics.

> Yes, Meg-4's docs look quite nice. I think it's well formatted.

Thanks! It was created from MarkDown using one of my other projects, gendoc.

> If it's displayed prominently then it should be easy to find

I deliberately haven't used any code hosting specific feature for the docs, I just put it in the repo itself. That way when you clone the repo, you'll get the docs too. Also it is embedded in the executable, at least the API reference part.

> Also, I might be able to help you with tinygl.

Thank you, I'd love that! I'm almost finished with it, I'm planning to upload to the repo today or maybe tomorrow. I'm just finishing up the docs for it.

> TinyGL was optimized by F. Bellard for old CPUs. the trirast code should be updated to use vector cross products to check whether a point is inside a triangle rather than using scanline techniques if you want it to go superspeed on a modern CPU (to take advantage of SIMD and whatnot)

Agreed. However I've removed everything and made it a plain simple implementation for portability (it has to work on WASM as well as on ARM). But I'm planning to add platform specific ifdef guards and have a SIMD optimized version too. Any help with that would be very much appreciated! Do you have a gitlab account? I believe it would be better to continue on a gitlab issue, not to disturb c-chads with this specific project.

Cheers,
bzt

**Comment by bztsrc** [comment]
Okay, I've uploaded the repo and created a gitlab issue too, with all the details how TinyGL was integrated.

**Comment by gek169** [comment]
thanks
