### ISSUE TITLE
C-Chads Membership

### ISSUE THREAD

**Issue by diamant3** [C-Chads/C-Chads#13]
Hi! My name is Diamond, and I would like to join for a badge on my profile and for a laugh because I don't have much experience. Anyway, I am using C much more than other languages

- Mostly I used C or sometimes Python/Lua

- The projects i made using C are these [psp-controller](https://github.com/diamant3/psp-controller) and [chip-walo](https://github.com/diamant3/chip-walo) and i contribute to [pspdev](https://github.com/pspdev) because they are using C for their SDK.

- Using Windows(I use it as a student) and sometimes Linux(When i need to contribute to open-source or want to try some Linux compatible apps/games or for dev same for windows).

Thanks!

**Comment by gek169** [comment]
Alright I'll send it to you

**Comment by gek169** [comment]
Invited!

**Comment by diamant3** [comment]
Thank you!
