### ISSUE TITLE
# I'd like to join

### ISSUE THREAD

**Issue by ShadowwLol** [C-Chads/C-Chads#5]
Hello, due to recent circunstances I've found myself looking to join the famous C-Chads group.

# Who am I?
I am a/an:

**B** right C programmer
**A** spiring full-time C-Chads developer
**S** upreme god-like code writer
**E** ndeavorous code inventor
**D** efinitely the chaddest C programmer

# Experience
* I have many open-source C projects
* I have over 100 years of C experience (pls don't check :( )

# Conclusion
I await my inevitable acceptance into this group.

**Comment by gek169** [comment]
i will invite you

**Comment by gek169** [comment]
Invited! Closing...
