### ISSUE TITLE
Would like to join

### ISSUE THREAD

**Issue by bztsrc** [C-Chads/C-Chads#6]
Hi,

I like the C-Chads philosophy very much, aligns with mine pretty well. (Except in using `goto`-s, I believe those can be extremely helpful and can keep the source more manageable in *experienced* hands. Easy to abuse them, true, but you won't ban a kitchen knife just because it could be used for bad things too.)

A few projects that I wrote and you could add to C-Chads if you'd like. All of them are stb-style single header libraries written in ANSI C89 (so yep, no `//` comments in my code!), licensed under MIT.

- [jsonc](https://gitlab.com/bztsrc/jsonc) Memory allocation-free, extremely fast JSON parser in pure ANSI C
- [rle](https://gitlab.com/bztsrc/rle) Dependency-free, extremely fast, TGA compatible RLE lib (supports 8, 16, 24 and 32 bits)
- [sqlite3aes](https://gitlab.com/bztsrc/sqlite3aes) Dependency-free AES encryption for SQLite3 in a single ANSI C header file
- [sdlogv](https://gitlab.com/bztsrc/sdlogv) Single header lib to play embedded theora videos in SDL applications.
- [tok](https://gitlab.com/bztsrc/tok) Single header source code tokenizer written in ANSI C
- [NetQ](https://gitlab.com/bztsrc/netq) Single header reliable datagram library written in ANSI C

Bonus:
- [brainfuck](https://gitlab.com/bztsrc/brainfuck) Brainfuck interpreter **and compiler** with optimizer and ELF output.

I have lots of other projects too (like Scalable Screen Font, Model3D, POSIX-UEFI, gendoc, bztalloc, etc. check out my [gitlab](https://gitlab.com/users/bztsrc/projects)), all of them are FOSS, but I definitely don't want them to be mirrored here on github given the cleptomaniac nature of CoPilot. Hope you understand. The list above contains just a few side projects of mine I don't care about too much.

Cheers,
bzt

**Comment by gek169** [comment]
I accept. Let me invite you.

**Comment by gek169** [comment]
You have been invited!

**Comment by gek169** [comment]
Since you know something about compiler authorship, i'd like to chat with you sometime...

**Comment by bztsrc** [comment]
Thank you!

> Since you know something about compiler authorship, i'd like to chat with you sometime...

I'm not much of a social type, I don't really like real-time chats, but I regularly read and answer my emails. The address given on the github profile works (bztemail at big G's mail server).

But sure, I like discussing technologies very much, and I'm really into compilers and stuff. I'm working on one right now, it has a [visual interface](https://forum.freegamedev.net/download/file.php?id=14490&mode=view) (tnge is the editor, tngd is the debugger) with dragn'n'drop, a textual [C-like save format](https://codeberg.org/tirnanog/editor/src/branch/main/docs/proj_format.md#user-content-event-handlers), and compiles to a [bytecode](https://codeberg.org/tirnanog/editor/src/branch/main/docs/tng_format.md#user-content-script-assets). It is pretty specific to the project I'm working on of course. What makes it special and me proud is that its VM is self-optimizing: whenever it runs into an opcode which can only be interpreted in O(n) time, then it replaces that with an O(1) opcode as it runs :-)

Cheers,
bzt
