### ISSUE TITLE
Joining request

### ISSUE THREAD

**Issue by TSOA2** [C-Chads/C-Chads#7]
I found your organization and liked a lot of the repos in it. 

- I like C and Linux
- I'm not an experienced developer, nor do I have any big projects that I'm working on -- I am an aspiring C-Chad
- I'd like to learn from your repos, they look very cool
- I hope to contribute a repo when I get more experienced
- I don't like Windows for programming (or generally anything)

Thank you for your time,
tsoa

**Comment by gek169** [comment]
Sure!

**Comment by gek169** [comment]
@TSOA2 It has been sent!
