### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by bratpeki** [C-Chads/C-Chads#8]
You already know the deal, baby!

**Comment by bratpeki** [comment]
A bit about me is available on my GitHub profile, but as for my C skills:

- I made a [pretty basic SDL2 boilerplate project using C](https://github.com/bratpeki/c-sdl2-boilerplate)
- I made a [text-based graphing library](https://github.com/bratpeki/grap.h)
- I had a project which was a [chess application, aimed specifically at learning chess](https://github.com/bratpeki/teachess), the development has current been halted because...
- I am currently in college, getting to know C even better, at a computer level

I would love to work with you, after reviewing your C standards, "Orthodox" approach to C++ and various projects that you have undertaken!

My knowledge has plenty of room for expansion and I'd love to learn about C with and from you! :)

**Comment by gek169** [comment]
alrighty I'll send you an invite
